# adapted from https://github.com/flatpak/flatpak-github-actions

on:
  push:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: palette.flatpak
        manifest-path: flatpak/berlin.giz.Quba.yml
        cache-key: flatpak-builder-${{ github.sha }}
    - uses: actions/download-artifact@v4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: palette-x86_64
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: palette-x86_64
    # - uses: flatpak/flatpak-github-actions/flat-manager@v6
    #   name: "Deploy"
    #   with:
    #     repository: elementary
    #     flat-manager-url: https://flatpak-api.elementary.io
    #     token: some_very_hidden_token
