# adapted from https://github.com/flatpak/flatpak-github-actions

on:
  push:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: palette.flatpak
        manifest-path: flatpak/berlin.giz.Quba.yml
        cache-key: flatpak-builder-${{ github.sha }}
